### ISSUE TITLE
URL which cantains * and at least one character after it doesn't become link

### ISSUE THREAD

**Issue by akihisa1210** [ganta/chrome-extension-marktone#14]
Thank you for your useful extension!
I found a strange vehavior.

`http://example.com/a=*a` becomes

```
<p style="margin: 0px 0px 16px;"><a>http://example.com/?a=*a</a></p>
```
There is no "href" attribute.

[Notes:]

`http://example.com/?a=a` becomes

```
<p style="margin: 0px 0px 16px;"><a href="http://example.com/?a=a" rel="nofollow">http://example.com/?a=a</a></p>
```
(no problems)

And

`http://example.com/?a=*` becomes

```
<p style="margin: 0px 0px 16px;"><a href="http://example.com/?a=" rel="nofollow">http://example.com/?a=</a>*</p>
```
(no problems, too)

**Comment by ganta** [comment]
In the preview, the `*` at the end of a URL does not become a link because of the Markdown parser.
This is probably because `*` is used in the bold or italic format.

It is a kintone problem that the href attribute is removed after posting.

Therefore, there is no plan to deal with anything on the Marktone side.
